"""new fields in user model

Revision ID: 76643e213ea0
Revises: 7b7fdbfaee53
Create Date: 2019-11-02 16:24:16.349022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76643e213ea0'
down_revision = '7b7fdbfaee53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
